question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "The shortest war in history lasted only 38 minutes.", "answer": "True"},
    {"text": "Bananas are berries.", "answer": "True"},
    {"text": "The Great Wall of China is visible from space.", "answer": "False"},
    {"text": "The dot over the letter 'i' is called a tittle.", "answer": "True"},
    {"text": "Octopuses have three hearts.", "answer": "True"},
    {"text": "Polar bears are left-handed.", "answer": "False"},
    {"text": "The Eiffel Tower can be 15 cm taller during the summer.", "answer": "True"},
    {"text": "Mosquitoes have teeth.", "answer": "False"},
    {"text": "Coca-Cola was originally green.", "answer": "True"},
    {"text": "The unicorn is the national animal of Scotland.", "answer": "True"},
    {"text": "Cows moo with regional accents.", "answer": "True"},
    {"text": "There are more fake flamingos than real ones.", "answer": "True"},
    {"text": "An octopus has three hearts.", "answer": "True"},
    {"text": "The world’s oldest piece of chewing gum is over 9,000 years old.", "answer": "True"},
    {"text": "Honey never spoils.", "answer": "True"},
    {"text": "Baby porcupines are called porcupettes.", "answer": "True"},
    {"text": "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.", "answer": "True"},
    {"text": "The total weight of all the ants on Earth is about the same as the weight of all the humans.", "answer": "True"},
    {"text": "The moon has moonquakes.", "answer": "True"},
    {"text": "There is a city called Rome on every continent.", "answer": "True"},
    {"text": "A day on Venus is longer than a year on Venus.", "answer": "True"},
    {"text": "The name for the shape of Pringles is called a 'Hyperbolic Paraboloid'.", "answer": "True"},
    {"text": "The shortest war in history lasted only 38 minutes.", "answer": "True"},
    {"text": "The unicorn is the national animal of Scotland.", "answer": "True"},
    {"text": "Honey never spoils.", "answer": "True"},
    {"text": "Cows moo with regional accents.", "answer": "True"},
    {"text": "Polar bears are left-handed.", "answer": "False"},
    {"text": "The Great Wall of China is visible from space.", "answer": "False"},
    {"text": "The dot over the letter 'i' is called a tittle.", "answer": "True"},
    {"text": "Bananas are berries.", "answer": "True"},
    {"text": "Octopuses have three hearts.", "answer": "True"},
    {"text": "Coca-Cola was originally green.", "answer": "True"},
    {"text": "Mosquitoes have teeth.", "answer": "False"},
    {"text": "A group of flamingos is called a 'flamboyance'.", "answer": "True"},
    {"text": "A crocodile cannot stick its tongue out.", "answer": "True"},
    {"text": "The only letter that doesn't appear in any U.S. state name is the letter 'Q'.", "answer": "True"},
    {"text": "The elephant is the only mammal that can't jump.", "answer": "True"},
    {"text": "Blue whales are the largest animals on Earth.", "answer": "True"},
    {"text": "The longest English word is 189,819 letters long and would take you more than 3 hours to pronounce.", "answer": "True"},
    {"text": "A snail can sleep for 3 years.", "answer": "True"},
    {"text": "The longest time between two twins being born is 87 days.", "answer": "True"},
    {"text": "A shrimp's heart is in its head.", "answer": "True"},
    {"text": "Ants never sleep.", "answer": "True"},
    {"text": "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.", "answer": "True"},
    {"text": "The total weight of all the ants on Earth is about the same as the weight of all the humans.", "answer": "True"},
    {"text": "The moon has moonquakes.", "answer": "True"},
    {"text": "There is a city called Rome on every continent.", "answer": "True"},
    {"text": "A day on Venus is longer than a year on Venus.", "answer": "True"},
    {"text": "The name for the shape of Pringles is called a 'Hyperbolic Paraboloid'.", "answer": "True"},
    {"text": "A group of flamingos is called a 'flamboyance'.", "answer": "True"},
    {"text": "A crocodile cannot stick its tongue out.", "answer": "True"},
    {"text": "The only letter that doesn't appear in any U.S. state name is the letter 'Q'.", "answer": "True"},
    {"text": "The elephant is the only mammal that can't jump.", "answer": "True"},
    {"text": "Blue whales are the largest animals on Earth.", "answer": "True"},
    {"text": "The longest English word is 189,819 letters long and would take you more than 3 hours to pronounce.", "answer": "True"},
    {"text": "A snail can sleep for 3 years.", "answer": "True"},
    {"text": "The longest time between two twins being born is 87 days.", "answer": "True"},
    {"text": "A shrimp's heart is in its head.", "answer": "True"},
    {"text": "Ants never sleep.", "answer": "True"},
    {"text": "Cats have five toes on their front paws, but only four on their back paws.", "answer": "True"},
    {"text": "The opposite sides of a dice cube always add up to seven.", "answer": "True"},
    {"text": "Bees can recognize human faces.", "answer": "True"},
    {"text": "The shortest war in history lasted only 38 minutes.", "answer": "True"},
    {"text": "The unicorn is the national animal of Scotland.", "answer": "True"},
    {"text": "Honey never spoils.", "answer": "True"},
    {"text": "Cows moo with regional accents.", "answer": "True"},
    {"text": "Polar bears are left-handed.", "answer": "False"},
    {"text": "The Great Wall of China is visible from space.", "answer": "False"},
    {"text": "The dot over the letter 'i' is called a tittle.", "answer": "True"},
    {"text": "Bananas are berries.", "answer": "True"},
    {"text": "Octopuses have three hearts.", "answer": "True"},
    {"text": "Coca-Cola was originally green.", "answer": "True"},
    {"text": "Mosquitoes have teeth.", "answer": "False"},
    {"text": "A group of flamingos is called a 'flamboyance'.", "answer": "True"},
    {"text": "A crocodile cannot stick its tongue out.", "answer": "True"},
    {"text": "The only letter that doesn't appear in any U.S. state name is the letter 'Q'.", "answer": "True"},
    {"text": "The elephant is the only mammal that can't jump.", "answer": "True"},
    {"text": "Blue whales are the largest animals on Earth.", "answer": "True"},
    {"text": "The longest English word is 189,819 letters long and would take you more than 3 hours to pronounce.", "answer": "True"},
    {"text": "A snail can sleep for 3 years.", "answer": "True"},
    {"text": "The longest time between two twins being born is 87 days.", "answer": "True"},
    {"text": "A shrimp's heart is in its head.", "answer": "True"},
    {"text": "Ants never sleep.", "answer": "True"},
    {"text": "Cats have five toes on their front paws, but only four on their back paws.", "answer": "True"},
    {"text": "The opposite sides of a dice cube always add up to seven.", "answer": "True"},
    {"text": "Bees can recognize human faces.", "answer": "True"}
]
